default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: consumer_chat_development

test:
  <<: *default
  database: consumer_chat_test

production:
  <<: *default
  database: consumer_chat_production
  username: consumer_chat
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
